version: '3.7'
services:
  web:
    image: nginx:alpine
    environment:
      VIRTUAL_HOST: r9cop.itgis.innovateteam.com
      VIRTUAL_PORT: 80
      VIRTUAL_PROTO: http
      LETSENCRYPT_HOST: r9cop.itgis.innovateteam.com
      LETSENCRYPT_EMAIL: tbock@innovateteam.com
    expose:
      - "80"
    restart: unless-stopped
    networks:
      - proxy
      - default
    volumes:
      - .:/usr/share/nginx/html
      - ./template.nginx:/etc/nginx/conf.d/default.conf
    command: nginx -g 'daemon off;'

networks:
  proxy:
    name: nginx_proxy_default
