on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

name: check and deploy app
jobs:

  check:
    runs-on: self-hosted
    outputs:
      continue: ${{ steps.check.outputs.continue }}
    steps:
      - name: check if changes to json file
        id: check
        run: |
          $info = Get-Content .\info.json -Raw | ConvertFrom-Json
          $now = Get-Date -UFormat %s
          $continue = $info.typeKeywords -contains "status: Draft" -and [float]$now * 1000 - $info.modified -lt 600000
          echo "continue=$continue" >> $env:GITHUB_ENV
          echo $continue
        working-directory: ${{vars.EB_LOCATION}}\server\public\apps\12

  deploy_staging:
    needs: check
    if: ${{ needs.check.outputs.continue == 'true' }}
    runs-on: self-hosted
    environment: NEW_ER_CLOUD
    env:
      BACKUP: \\${{vars.WEB_HOST}}\R9apps\staging\COP_backup
      LATEST: \\${{vars.WEB_HOST}}\R9apps\staging\COP_LATEST
      PROD: \\${{vars.WEB_HOST}}\R9apps\staging\cop
    steps:
      - name: remove backup and latest folders if exists
        run: |
          if (Test-Path $env:BACKUP) {
            Remove-Item -Recurse -Force $env:BACKUP
          }
          if (Test-Path $env:LATEST) {
            Remove-Item -Recurse -Force $env:LATEST
          }
          if (Test-Path ${{ github.workspace }}\exp_builder_widgets_export.zip) {
            Remove-Item -Force ${{ github.workspace }}\exp_builder_widgets_export.zip
          }
      - name: export app to zip and unpack into latest folder
        working-directory: ${{vars.EB_LOCATION}}
        run: |
          node -e "require('./server/src/middlewares/dev/apps/app-download.js').zipApp('12', '${{ github.workspace }}\exp_builder_widgets_export.zip', '${{vars.COP_CLIENT_ID}}');"
          Expand-Archive -LiteralPath ${{ github.workspace }}\exp_builder_widgets_export.zip -DestinationPath $env:LATEST

      - name: move prod to backup and latest to prod
        run: |
          Rename-Item $env:PROD $env:BACKUP
          Rename-Item $env:LATEST $env:PROD

