on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:
  deployment_status:
    environment: EB
    state: success

name: check and deploy app
jobs:

  check:
    if: github.event_name != 'deployment_status'
    runs-on: self-hosted
    outputs:
      continue: ${{ steps.check.outputs.continue }}
    steps:
      - name: check if changes to json file
        id: check
        run: |
          $info = Get-Content .\info.json -Raw | ConvertFrom-Json
          $lastDeploy = Get-Date -Date (Get-Item \\${{vars.WEB_HOST}}\R9apps\staging\cop).LastWriteTime -UFormat "%s"
          $continue = $info.typeKeywords -contains "status: Published" -and $lastDeploy - $info.modified /1000 -lt 0
          echo "continue=$continue" >> $env:GITHUB_OUTPUT
          echo $continue
        working-directory: ${{vars.EB_LOCATION}}\server\public\apps\${{vars.BUILD_ID}}

  deploy_staging:
    if: ${{ needs.check.outputs.continue == 'True' || github.event_name == 'deployment_status' }}
    runs-on: self-hosted
    environment: NEW_ER_CLOUD
    env:
      BACKUP: \\${{vars.WEB_HOST}}\R9apps\staging\COP_backup
      LATEST: \\${{vars.WEB_HOST}}\R9apps\staging\COP_LATEST
      PROD: \\${{vars.WEB_HOST}}\R9apps\staging\cop
    steps:
      - name: remove backup and latest folders if exists
        run: |
          if (Test-Path $env:BACKUP) {
            Remove-Item -Recurse -Force $env:BACKUP
          }
          if (Test-Path $env:LATEST) {
            Remove-Item -Recurse -Force $env:LATEST
          }
          if (Test-Path ${{ github.workspace }}\exp_builder_widgets_export.zip) {
            Remove-Item -Force ${{ github.workspace }}\exp_builder_widgets_export.zip
          }
      - name: export app to zip and unpack into latest folder
        working-directory: ${{vars.EB_LOCATION}}
        run: |
          $zipPath = '${{ github.workspace }}\exp_builder_widgets_export.zip'.Replace('\', '/')
          node -e "require('./server/src/middlewares/dev/apps/app-download.js').zipApp('${{ vars.BUILD_ID }}', '$zipPath', '${{vars.COP_CLIENT_ID}}');"
          Expand-Archive -LiteralPath ${{ github.workspace }}\exp_builder_widgets_export.zip -DestinationPath $env:LATEST

      - name: move prod to backup and latest to prod
        run: |
          Rename-Item $env:PROD $env:BACKUP
          Rename-Item $env:LATEST $env:PROD

