name: Debug Deployment Status

on:
  deployment_status:
    types: [success]

jobs:
  debug-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Event Details
        env:
          DEPLOYMENT_STATUS: ${{ toJson(github.event) }}
        run: echo "$DEPLOYMENT_STATUS"
