name: deploy widgets

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: copy to EB client
        run: |
          $destination = "D:\R9Web\ArcGISExperienceBuilder\client\R9-Widgets"
          Remove-Item -Recurse -Force $destination
          New-Item -Path ${{ inputs.destination }} -ItemType directory
          Copy-Item -Path ${{ github.workspace }}\* -Destination $destination  -Recurse

      - name: install deps and build
        run: |
          npm ci
          npm run build:dev
          npm run build:prod
        working-directory: D:\R9Web\ArcGISExperienceBuilder\client
        
