name: deploy widgets

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: copy to EB client
        run: |
          Remove-Item -Recurse -Force D:\R9Web\ArcGISExperienceBuilder\client\R9-Widgets
          Copy-Item -Path ${{ github.workspace }}\* -Destination D:\R9Web\ArcGISExperienceBuilder\client\R9-Widgets -Recurse

      - name: install deps and build
        run: |
          npm ci
          npm run build:dev
          npm run build:prod
        working-directory: D:\R9Web\ArcGISExperienceBuilder\client
        
